[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.64.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://elated-tesla-7b3352.netlify.app/"
