baseURL: https://bershatsky.net
languageCode: en-us
title: Noah Bershatsky
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name:
    pre: home
    url: /
    weight: 1
  - name:
    pre: edit
    url: /post/
    weight: 2
  - name:
    pre: tag
    url: /tags/
    weight: 3
  - name:
    pre: smile
    url: /about/
    weight: 4
  - name:
    pre: rss
    url: /index.xml
    weight: 5
  - name:
    pre: image
    url: /portfolio/
    weight: 6
    

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 800px
  dateFormat: Jan 2, 2006
  homeText: Photographer | Blogger | Black Belt | Family Man | My cat is 20 years old.
  footerText: Copyright 2020 - All rights reserved.
  hideFooter: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
